// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awzmnsxxbkprgpnxbahm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3em1uc3h4YmtwcmdwbnhiYWhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NTE0NzksImV4cCI6MjA2MzUyNzQ3OX0.5VkKoO5YXuBMcEq90hjZRAX3foEqHU3hYqU8PmTQnto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);